### ISSUE TITLE
佬，这个脚本是自动执行的吗

### ISSUE THREAD

**Issue by IGNiT3-R** [Sliverkiss/Serv00_Auto_Login#2]
佬，我不太懂，想问一下，这个脚本配置好了是隔多久自动执行的吗？还是需要我自己手动来执行呀？

**Comment by Sliverkiss** [comment]
> 佬，我不太懂，想问一下，这个脚本配置好了是隔多久自动执行的吗？还是需要我自己手动来执行呀？

定时运行，可以在yml文件修改cron配置
